global script_node

global function Interact()
end

global function wake_cybermen()
	local doctor=GetActor("doctor")
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()

	Wait(0.2)
	doctor:SetBehaviour("wait")

	NanoMinigame:Easy()
	MinigameManager:SetCallback(script_node, "Run_cutscene")
	MinigameManager:StartMiniGame(NanoMinigame)
end

global function Run_cutscene()
	local cutscene = FindNodeByName("Cutscene_12")
	cutscene:Trigger()
end

global function snooze_cybermen()
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()

	HideLetterBox()
	
	--Get back tot the control room
	SetGlobalObjectiveState("Cyber_3_6_1", 3) -- 2 is unlock, 3 is done
	
	Wait(1)
	NanoMinigame:Easy()
	MinigameManager:SetCallback(script_node, "Run_cutscene_sabotage")
	MinigameManager:StartMiniGame(NanoMinigame)
end

global function Run_cutscene_sabotage()
	local cutscene = FindNodeByName("Cutscene_14")
	cutscene:Trigger()
end

global function Trigger()
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()

	MinigameManager:StartMiniGame(NanoMinigame)

	NanoMinigame:AddDoubleCondition(5,1,3,0,0)
	NanoMinigame:SetCatalystColour(0,5)
	NanoMinigame:SetCatalystActive(0,1)
	NanoMinigame:SetCatalystColour(1,3)
	NanoMinigame:SetCatalystActive(1,1)
	NanoMinigame:SetCatalystColour(2,0)
	NanoMinigame:SetCatalystActive(2,0)
	NanoMinigame:SetCatalystColour(3,0)
	NanoMinigame:SetCatalystActive(3,0)
	NanoMinigame:SetCatalystColour(4,2)
	NanoMinigame:SetCatalystActive(4,1)
	NanoMinigame:SetCatalystColour(5,0)
	NanoMinigame:SetCatalystActive(5,0)
	NanoMinigame:SetCatalystColour(6,4)
	NanoMinigame:SetCatalystActive(6,1)
	NanoMinigame:SetCatalystColour(7,0)
	NanoMinigame:SetCatalystActive(7,0)
	NanoMinigame:SetTargetColour(0,0,2)
	NanoMinigame:SetTargetActive(0,0,1)
	NanoMinigame:SetTargetVolatile(0,0,0)
	NanoMinigame:SetTargetColour(0,1,3)
	NanoMinigame:SetTargetActive(0,1,1)
	NanoMinigame:SetTargetVolatile(0,1,0)
	NanoMinigame:SetTargetColour(0,2,0)
	NanoMinigame:SetTargetActive(0,2,0)
	NanoMinigame:SetTargetVolatile(0,2,0)
	NanoMinigame:SetTargetColour(0,3,2)
	NanoMinigame:SetTargetActive(0,3,1)
	NanoMinigame:SetTargetVolatile(0,3,0)
	NanoMinigame:SetTargetColour(0,4,4)
	NanoMinigame:SetTargetActive(0,4,1)
	NanoMinigame:SetTargetVolatile(0,4,0)
	NanoMinigame:SetTargetColour(0,5,0)
	NanoMinigame:SetTargetActive(0,5,0)
	NanoMinigame:SetTargetVolatile(0,5,0)
	NanoMinigame:SetTargetColour(0,6,0)
	NanoMinigame:SetTargetActive(0,6,0)
	NanoMinigame:SetTargetVolatile(0,6,0)
	NanoMinigame:SetTargetColour(0,7,0)
	NanoMinigame:SetTargetActive(0,7,0)
	NanoMinigame:SetTargetVolatile(0,7,0)
	NanoMinigame:SetTargetColour(0,8,4)
	NanoMinigame:SetTargetActive(0,8,1)
	NanoMinigame:SetTargetVolatile(0,8,0)
	NanoMinigame:SetTargetColour(0,9,5)
	NanoMinigame:SetTargetActive(0,9,1)
	NanoMinigame:SetTargetVolatile(0,9,0)
	NanoMinigame:SetTargetColour(0,10,5)
	NanoMinigame:SetTargetActive(0,10,1)
	NanoMinigame:SetTargetVolatile(0,10,0)
	NanoMinigame:SetTargetColour(0,11,0)
	NanoMinigame:SetTargetActive(0,11,0)
	NanoMinigame:SetTargetVolatile(0,11,0)
	NanoMinigame:SetTargetSpeed(10)
	NanoMinigame:SetTargetColour(1,0,3)
	NanoMinigame:SetTargetActive(1,0,1)
	NanoMinigame:SetTargetVolatile(1,0,0)
	NanoMinigame:SetTargetColour(1,1,0)
	NanoMinigame:SetTargetActive(1,1,0)
	NanoMinigame:SetTargetVolatile(1,1,0)
	NanoMinigame:SetTargetColour(1,2,0)
	NanoMinigame:SetTargetActive(1,2,1)
	NanoMinigame:SetTargetVolatile(1,2,1)
	NanoMinigame:SetTargetColour(1,3,0)
	NanoMinigame:SetTargetActive(1,3,0)
	NanoMinigame:SetTargetVolatile(1,3,0)
	NanoMinigame:SetTargetColour(1,4,0)
	NanoMinigame:SetTargetActive(1,4,0)
	NanoMinigame:SetTargetVolatile(1,4,0)
	NanoMinigame:SetTargetColour(1,5,0)
	NanoMinigame:SetTargetActive(1,5,0)
	NanoMinigame:SetTargetVolatile(1,5,0)
	NanoMinigame:SetTargetColour(1,6,0)
	NanoMinigame:SetTargetActive(1,6,0)
	NanoMinigame:SetTargetVolatile(1,6,0)
	NanoMinigame:SetTargetColour(1,7,2)
	NanoMinigame:SetTargetActive(1,7,1)
	NanoMinigame:SetTargetVolatile(1,7,0)
	NanoMinigame:SetTargetColour(1,8,5)
	NanoMinigame:SetTargetActive(1,8,1)
	NanoMinigame:SetTargetVolatile(1,8,0)
	NanoMinigame:SetTargetColour(1,9,0)
	NanoMinigame:SetTargetActive(1,9,0)
	NanoMinigame:SetTargetVolatile(1,9,0)
	NanoMinigame:SetTargetColour(1,10,0)
	NanoMinigame:SetTargetActive(1,10,0)
	NanoMinigame:SetTargetVolatile(1,10,0)
	NanoMinigame:SetTargetColour(1,11,0)
	NanoMinigame:SetTargetActive(1,11,0)
	NanoMinigame:SetTargetVolatile(1,11,0)
	NanoMinigame:SetTargetSpeed(12)

	MinigameManager:StartMiniGame(NanoMinigame)
end