global function EnableDalekStealth()
	local dalek = GetActor("dalek")
	local dalek1 = GetActor("dalek1")
	local dalek2 = GetActor("dalek2")
	local dalek3 = GetActor("dalek3")
	local dalek4 = GetActor("dalek4")
	local dalek5 = GetActor("dalek5")
	
	dalek:EnableSensorVisuals(true)
	dalek1:EnableSensorVisuals(true)
	dalek2:EnableSensorVisuals(true)
	dalek3:EnableSensorVisuals(true)
	dalek4:EnableSensorVisuals(true)
	dalek5:EnableSensorVisuals(true)
end