
global script_node
local which_game = 3





global function Hard()
	Wait(3)
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()
	MinigameManager:SetMiniGameID("MINI_NANO03")
	NanoMinigame:Hard()
	NanoMinigame:SetEnvironment(1)
	
	NanoMinigame:ResetConditions()
	NanoMinigame:AddDoubleCondition(3,3,1,0,0)
	NanoMinigame:AddDoubleCondition(5,3,4,0,0)
	NanoMinigame:SetCatalystColour(0,3)
	NanoMinigame:SetCatalystActive(0,1)
	NanoMinigame:SetCatalystColour(1,0)
	NanoMinigame:SetCatalystActive(1,0)
	NanoMinigame:SetCatalystColour(2,1)
	NanoMinigame:SetCatalystActive(2,1)
	NanoMinigame:SetCatalystColour(4,4)
	NanoMinigame:SetCatalystActive(4,1)
	NanoMinigame:SetCatalystColour(3,5)
	NanoMinigame:SetCatalystActive(3,1)
	NanoMinigame:SetCatalystColour(5,0)
	NanoMinigame:SetCatalystActive(5,0)
	NanoMinigame:SetCatalystColour(6,0)
	NanoMinigame:SetCatalystActive(6,0)
	NanoMinigame:SetCatalystColour(7,0)
	NanoMinigame:SetCatalystActive(7,0)
	NanoMinigame:SetTargetColour(0,0,0)
	NanoMinigame:SetTargetActive(0,0,0)
	NanoMinigame:SetTargetVolatile(0,0,0)
	NanoMinigame:SetTargetColour(0,1,0)
	NanoMinigame:SetTargetActive(0,1,0)
	NanoMinigame:SetTargetVolatile(0,1,0)
	NanoMinigame:SetTargetColour(0,2,4)
	NanoMinigame:SetTargetActive(0,2,1)
	NanoMinigame:SetTargetVolatile(0,2,0)
	NanoMinigame:SetTargetColour(0,3,4)
	NanoMinigame:SetTargetActive(0,3,0)
	NanoMinigame:SetTargetVolatile(0,3,1)
	NanoMinigame:SetTargetColour(0,4,0)
	NanoMinigame:SetTargetActive(0,4,0)
	NanoMinigame:SetTargetVolatile(0,4,0)
	NanoMinigame:SetTargetColour(0,5,0)
	NanoMinigame:SetTargetActive(0,5,0)
	NanoMinigame:SetTargetVolatile(0,5,0)
	NanoMinigame:SetTargetColour(0,6,1)
	NanoMinigame:SetTargetActive(0,6,1)
	NanoMinigame:SetTargetVolatile(0,6,0)
	NanoMinigame:SetTargetColour(0,7,0)
	NanoMinigame:SetTargetActive(0,7,0)
	NanoMinigame:SetTargetVolatile(0,7,0)
	NanoMinigame:SetTargetColour(0,8,0)
	NanoMinigame:SetTargetActive(0,8,0)
	NanoMinigame:SetTargetVolatile(0,8,0)
	NanoMinigame:SetTargetColour(0,9,5)
	NanoMinigame:SetTargetActive(0,9,1)
	NanoMinigame:SetTargetVolatile(0,9,0)
	NanoMinigame:SetTargetColour(0,10,0)
	NanoMinigame:SetTargetActive(0,10,0)
	NanoMinigame:SetTargetVolatile(0,10,0)
	NanoMinigame:SetTargetColour(0,11,1)
	NanoMinigame:SetTargetActive(0,11,1)
	NanoMinigame:SetTargetVolatile(0,11,0)
	NanoMinigame:SetTargetSpeed(0,0.85)
	NanoMinigame:SetTargetColour(1,0,4)
	NanoMinigame:SetTargetActive(1,0,1)
	NanoMinigame:SetTargetVolatile(1,0,0)
	NanoMinigame:SetTargetColour(1,1,0)
	NanoMinigame:SetTargetActive(1,1,0)
	NanoMinigame:SetTargetVolatile(1,1,0)
	NanoMinigame:SetTargetColour(1,2,0)
	NanoMinigame:SetTargetActive(1,2,0)
	NanoMinigame:SetTargetVolatile(1,2,0)
	NanoMinigame:SetTargetColour(1,3,0)
	NanoMinigame:SetTargetActive(1,3,0)
	NanoMinigame:SetTargetVolatile(1,3,0)
	NanoMinigame:SetTargetColour(1,4,1)
	NanoMinigame:SetTargetActive(1,4,1)
	NanoMinigame:SetTargetVolatile(1,4,1)
	NanoMinigame:SetTargetColour(1,5,0)
	NanoMinigame:SetTargetActive(1,5,0)
	NanoMinigame:SetTargetVolatile(1,5,0)
	NanoMinigame:SetTargetColour(1,6,0)
	NanoMinigame:SetTargetActive(1,6,0)
	NanoMinigame:SetTargetVolatile(1,6,0)
	NanoMinigame:SetTargetColour(1,7,1)
	NanoMinigame:SetTargetActive(1,7,1)
	NanoMinigame:SetTargetVolatile(1,7,0)
	NanoMinigame:SetTargetColour(1,8,0)
	NanoMinigame:SetTargetActive(1,8,0)
	NanoMinigame:SetTargetVolatile(1,8,0)
	NanoMinigame:SetTargetColour(1,9,0)
	NanoMinigame:SetTargetActive(1,9,0)
	NanoMinigame:SetTargetVolatile(1,9,0)
	NanoMinigame:SetTargetColour(1,10,1)
	NanoMinigame:SetTargetActive(1,10,1)
	NanoMinigame:SetTargetVolatile(1,10,1)
	NanoMinigame:SetTargetColour(1,11,0)
	NanoMinigame:SetTargetActive(1,11,0)
	NanoMinigame:SetTargetVolatile(1,11,0)
	NanoMinigame:SetTargetSpeed(1,0.45)

	MinigameManager:StartMiniGame(NanoMinigame)

end






global function Medium()
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()
	MinigameManager:SetMiniGameID("MINI_NANO01")
	NanoMinigame:Medium()
	
	NanoMinigame:ResetConditions()
NanoMinigame:AddDoubleCondition(5,1,4,0,0)
NanoMinigame:AddDoubleCondition(1,3,3,0,0)
NanoMinigame:SetCatalystColour(0,1)
NanoMinigame:SetCatalystActive(0,1)
NanoMinigame:SetCatalystColour(1,0)
NanoMinigame:SetCatalystActive(1,0)
NanoMinigame:SetCatalystColour(2,3)
NanoMinigame:SetCatalystActive(2,1)
NanoMinigame:SetCatalystColour(3,5)
NanoMinigame:SetCatalystActive(3,1)
NanoMinigame:SetCatalystColour(4,0)
NanoMinigame:SetCatalystActive(4,0)
NanoMinigame:SetCatalystColour(5,0)
NanoMinigame:SetCatalystActive(5,0)
NanoMinigame:SetCatalystColour(6,0)
NanoMinigame:SetCatalystActive(6,0)
NanoMinigame:SetCatalystColour(7,6)
NanoMinigame:SetCatalystActive(7,1)
NanoMinigame:SetTargetColour(0,0,0)
NanoMinigame:SetTargetActive(0,0,0)
NanoMinigame:SetTargetVolatile(0,0,0)
NanoMinigame:SetTargetColour(0,1,3)
NanoMinigame:SetTargetActive(0,1,1)
NanoMinigame:SetTargetVolatile(0,1,0)
NanoMinigame:SetTargetColour(0,2,0)
NanoMinigame:SetTargetActive(0,2,0)
NanoMinigame:SetTargetVolatile(0,2,0)
NanoMinigame:SetTargetColour(0,3,0)
NanoMinigame:SetTargetActive(0,3,0)
NanoMinigame:SetTargetVolatile(0,3,0)
NanoMinigame:SetTargetColour(0,4,1)
NanoMinigame:SetTargetActive(0,4,1)
NanoMinigame:SetTargetVolatile(0,4,0)
NanoMinigame:SetTargetColour(0,5,1)
NanoMinigame:SetTargetActive(0,5,1)
NanoMinigame:SetTargetVolatile(0,5,0)
NanoMinigame:SetTargetColour(0,6,3)
NanoMinigame:SetTargetActive(0,6,1)
NanoMinigame:SetTargetVolatile(0,6,0)
NanoMinigame:SetTargetColour(0,7,0)
NanoMinigame:SetTargetActive(0,7,0)
NanoMinigame:SetTargetVolatile(0,7,0)
NanoMinigame:SetTargetColour(0,8,3)
NanoMinigame:SetTargetActive(0,8,1)
NanoMinigame:SetTargetVolatile(0,8,0)
NanoMinigame:SetTargetColour(0,9,0)
NanoMinigame:SetTargetActive(0,9,0)
NanoMinigame:SetTargetVolatile(0,9,0)
NanoMinigame:SetTargetColour(0,10,0)
NanoMinigame:SetTargetActive(0,10,0)
NanoMinigame:SetTargetVolatile(0,10,0)
NanoMinigame:SetTargetColour(0,11,3)
NanoMinigame:SetTargetActive(0,11,1)
NanoMinigame:SetTargetVolatile(0,11,0)
NanoMinigame:SetTargetSpeed(0,0.6)
NanoMinigame:SetTargetColour(1,0,0)
NanoMinigame:SetTargetActive(1,0,0)
NanoMinigame:SetTargetVolatile(1,0,0)
NanoMinigame:SetTargetColour(1,1,0)
NanoMinigame:SetTargetActive(1,1,0)
NanoMinigame:SetTargetVolatile(1,1,0)
NanoMinigame:SetTargetColour(1,2,5)
NanoMinigame:SetTargetActive(1,2,1)
NanoMinigame:SetTargetVolatile(1,2,0)
NanoMinigame:SetTargetColour(1,3,3)
NanoMinigame:SetTargetActive(1,3,0)
NanoMinigame:SetTargetVolatile(1,3,0)
NanoMinigame:SetTargetColour(1,4,5)
NanoMinigame:SetTargetActive(1,4,1)
NanoMinigame:SetTargetVolatile(1,4,0)
NanoMinigame:SetTargetColour(1,5,0)
NanoMinigame:SetTargetActive(1,5,0)
NanoMinigame:SetTargetVolatile(1,5,0)
NanoMinigame:SetTargetColour(1,6,4)
NanoMinigame:SetTargetActive(1,6,1)
NanoMinigame:SetTargetVolatile(1,6,0)
NanoMinigame:SetTargetColour(1,7,0)
NanoMinigame:SetTargetActive(1,7,0)
NanoMinigame:SetTargetVolatile(1,7,0)
NanoMinigame:SetTargetColour(1,8,5)
NanoMinigame:SetTargetActive(1,8,1)
NanoMinigame:SetTargetVolatile(1,8,0)
NanoMinigame:SetTargetColour(1,9,0)
NanoMinigame:SetTargetActive(1,9,0)
NanoMinigame:SetTargetVolatile(1,9,0)
NanoMinigame:SetTargetColour(1,10,0)
NanoMinigame:SetTargetActive(1,10,0)
NanoMinigame:SetTargetVolatile(1,10,0)
NanoMinigame:SetTargetColour(1,11,0)
NanoMinigame:SetTargetActive(1,11,1)
NanoMinigame:SetTargetVolatile(1,11,1)
NanoMinigame:SetTargetSpeed(1,-0.4)

	
	
	MinigameManager:StartMiniGame(NanoMinigame)
	MinigameManager:SetCallback(script_node, "Hard")
end


global function Easy()
	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()
	MinigameManager:SetMiniGameID("MINI_NANO01")
	NanoMinigame:Easy()

NanoMinigame:ResetConditions()
NanoMinigame:AddDoubleCondition(4,3,2,0,0)
NanoMinigame:AddDoubleCondition(3,1,2,0,0)
NanoMinigame:SetCatalystColour(0,3)
NanoMinigame:SetCatalystActive(0,1)
NanoMinigame:SetCatalystColour(1,0)
NanoMinigame:SetCatalystActive(1,0)
NanoMinigame:SetCatalystColour(2,4)
NanoMinigame:SetCatalystActive(2,1)
NanoMinigame:SetCatalystColour(3,6)
NanoMinigame:SetCatalystActive(3,1)
NanoMinigame:SetCatalystColour(4,0)
NanoMinigame:SetCatalystActive(4,0)
NanoMinigame:SetCatalystColour(5,2)
NanoMinigame:SetCatalystActive(5,1)
NanoMinigame:SetCatalystColour(6,0)
NanoMinigame:SetCatalystActive(6,0)
NanoMinigame:SetCatalystColour(7,0)
NanoMinigame:SetCatalystActive(7,0)
NanoMinigame:SetTargetColour(0,0,0) --
NanoMinigame:SetTargetActive(0,0,0)  --
NanoMinigame:SetTargetVolatile(0,0,0) --
NanoMinigame:SetTargetColour(0,1,1)
NanoMinigame:SetTargetActive(0,1,0)
NanoMinigame:SetTargetVolatile(0,1,0)
NanoMinigame:SetTargetColour(0,2,0)
NanoMinigame:SetTargetActive(0,2,0)
NanoMinigame:SetTargetVolatile(0,2,0)
NanoMinigame:SetTargetColour(0,3,1)
NanoMinigame:SetTargetActive(0,3,0)
NanoMinigame:SetTargetVolatile(0,3,0)
NanoMinigame:SetTargetColour(0,4,0)
NanoMinigame:SetTargetActive(0,4,0)
NanoMinigame:SetTargetVolatile(0,4,0)
NanoMinigame:SetTargetColour(0,5,6)
NanoMinigame:SetTargetActive(0,5,1)
NanoMinigame:SetTargetVolatile(0,5,0)
NanoMinigame:SetTargetColour(0,6,6)
NanoMinigame:SetTargetActive(0,6,1)
NanoMinigame:SetTargetVolatile(0,6,0)
NanoMinigame:SetTargetColour(0,7,0)
NanoMinigame:SetTargetActive(0,7,0)
NanoMinigame:SetTargetVolatile(0,7,0)
NanoMinigame:SetTargetColour(0,8,4)
NanoMinigame:SetTargetActive(0,8,1)
NanoMinigame:SetTargetVolatile(0,8,0)
NanoMinigame:SetTargetColour(0,9,0)
NanoMinigame:SetTargetActive(0,9,0)
NanoMinigame:SetTargetVolatile(0,9,0)
NanoMinigame:SetTargetColour(0,10,0)
NanoMinigame:SetTargetActive(0,10,0)
NanoMinigame:SetTargetVolatile(0,10,0)
NanoMinigame:SetTargetColour(0,11,6)
NanoMinigame:SetTargetActive(0,11,0)
NanoMinigame:SetTargetVolatile(0,11,0)
NanoMinigame:SetTargetSpeed(0,0.9)
NanoMinigame:SetTargetColour(1,0,0)
NanoMinigame:SetTargetActive(1,0,0)
NanoMinigame:SetTargetVolatile(1,0,0)
NanoMinigame:SetTargetColour(1,1,0)
NanoMinigame:SetTargetActive(1,1,0)
NanoMinigame:SetTargetVolatile(1,1,0)
NanoMinigame:SetTargetColour(1,2,2)
NanoMinigame:SetTargetActive(1,2,1)
NanoMinigame:SetTargetVolatile(1,2,0)
NanoMinigame:SetTargetColour(1,3,0)
NanoMinigame:SetTargetActive(1,3,0)
NanoMinigame:SetTargetVolatile(1,3,0)
NanoMinigame:SetTargetColour(1,4,2)
NanoMinigame:SetTargetActive(1,4,1)
NanoMinigame:SetTargetVolatile(1,4,0)
NanoMinigame:SetTargetColour(1,5,0)
NanoMinigame:SetTargetActive(1,5,0)
NanoMinigame:SetTargetVolatile(1,5,0)
NanoMinigame:SetTargetColour(1,6,2)
NanoMinigame:SetTargetActive(1,6,1)
NanoMinigame:SetTargetVolatile(1,6,0)
NanoMinigame:SetTargetColour(1,7,0)
NanoMinigame:SetTargetActive(1,7,0)
NanoMinigame:SetTargetVolatile(1,7,0)
NanoMinigame:SetTargetColour(1,8,2)
NanoMinigame:SetTargetActive(1,8,1)
NanoMinigame:SetTargetVolatile(1,8,0)
NanoMinigame:SetTargetColour(1,9,0)
NanoMinigame:SetTargetActive(1,9,0)
NanoMinigame:SetTargetVolatile(1,9,0)
NanoMinigame:SetTargetColour(1,10,3)
NanoMinigame:SetTargetActive(1,10,0)
NanoMinigame:SetTargetVolatile(1,10,0)
NanoMinigame:SetTargetColour(1,11,2)
NanoMinigame:SetTargetActive(1,11,1)
NanoMinigame:SetTargetVolatile(1,11,0)
NanoMinigame:SetTargetSpeed(1,0.4)


	MinigameManager:StartMiniGame(NanoMinigame)
end


global function Tutorial()

	local MinigameManager = FindManagerByName("EmAdventureGame_MiniGameManager")
	local NanoMinigame = MinigameManager:GetNanoMiniGame()
	MinigameManager:SetMiniGameID("MINI_NANO01")
	NanoMinigame:Easy()

NanoMinigame:ResetConditions()
NanoMinigame:AddDoubleCondition(5,3,4,0,0)
NanoMinigame:SetCatalystColour(0,0)
NanoMinigame:SetCatalystActive(0,0)
NanoMinigame:SetCatalystColour(1,5)
NanoMinigame:SetCatalystActive(1,1)
NanoMinigame:SetCatalystColour(2,0)
NanoMinigame:SetCatalystActive(2,0)
NanoMinigame:SetCatalystColour(3,0)
NanoMinigame:SetCatalystActive(3,0)
NanoMinigame:SetCatalystColour(4,0)
NanoMinigame:SetCatalystActive(4,0)
NanoMinigame:SetCatalystColour(5,0)
NanoMinigame:SetCatalystActive(5,0)
NanoMinigame:SetCatalystColour(6,0)
NanoMinigame:SetCatalystActive(6,0)
NanoMinigame:SetCatalystColour(7,0)
NanoMinigame:SetCatalystActive(7,0)
NanoMinigame:SetTargetColour(0,0,0)
NanoMinigame:SetTargetActive(0,0,0)
NanoMinigame:SetTargetVolatile(0,0,0)
NanoMinigame:SetTargetColour(0,1,0)
NanoMinigame:SetTargetActive(0,1,0)
NanoMinigame:SetTargetVolatile(0,1,0)
NanoMinigame:SetTargetColour(0,2,0)
NanoMinigame:SetTargetActive(0,2,0)
NanoMinigame:SetTargetVolatile(0,2,0)
NanoMinigame:SetTargetColour(0,3,4)
NanoMinigame:SetTargetActive(0,3,1)
NanoMinigame:SetTargetVolatile(0,3,0)
NanoMinigame:SetTargetColour(0,4,0)
NanoMinigame:SetTargetActive(0,4,0)
NanoMinigame:SetTargetVolatile(0,4,0)
NanoMinigame:SetTargetColour(0,5,0)
NanoMinigame:SetTargetActive(0,5,0)
NanoMinigame:SetTargetVolatile(0,5,0)
NanoMinigame:SetTargetColour(0,6,4)
NanoMinigame:SetTargetActive(0,6,1)
NanoMinigame:SetTargetVolatile(0,6,0)
NanoMinigame:SetTargetColour(0,7,0)
NanoMinigame:SetTargetActive(0,7,0)
NanoMinigame:SetTargetVolatile(0,7,0)
NanoMinigame:SetTargetColour(0,8,4)
NanoMinigame:SetTargetActive(0,8,1)
NanoMinigame:SetTargetVolatile(0,8,0)
NanoMinigame:SetTargetColour(0,9,0)
NanoMinigame:SetTargetActive(0,9,0)
NanoMinigame:SetTargetVolatile(0,9,0)
NanoMinigame:SetTargetColour(0,10,0)
NanoMinigame:SetTargetActive(0,10,0)
NanoMinigame:SetTargetVolatile(0,10,0)
NanoMinigame:SetTargetColour(0,11,4)
NanoMinigame:SetTargetActive(0,11,1)
NanoMinigame:SetTargetVolatile(0,11,0)
NanoMinigame:SetTargetSpeed(0,0.7)
NanoMinigame:SetTargetColour(1,0,0)
NanoMinigame:SetTargetActive(1,0,0)
NanoMinigame:SetTargetVolatile(1,0,0)
NanoMinigame:SetTargetColour(1,1,4)
NanoMinigame:SetTargetActive(1,1,1)
NanoMinigame:SetTargetVolatile(1,1,0)
NanoMinigame:SetTargetColour(1,2,0)
NanoMinigame:SetTargetActive(1,2,0)
NanoMinigame:SetTargetVolatile(1,2,0)
NanoMinigame:SetTargetColour(1,3,0)
NanoMinigame:SetTargetActive(1,3,0)
NanoMinigame:SetTargetVolatile(1,3,0)
NanoMinigame:SetTargetColour(1,4,4)
NanoMinigame:SetTargetActive(1,4,1)
NanoMinigame:SetTargetVolatile(1,4,0)
NanoMinigame:SetTargetColour(1,5,0)
NanoMinigame:SetTargetActive(1,5,0)
NanoMinigame:SetTargetVolatile(1,5,0)
NanoMinigame:SetTargetColour(1,6,0)
NanoMinigame:SetTargetActive(1,6,0)
NanoMinigame:SetTargetVolatile(1,6,0)
NanoMinigame:SetTargetColour(1,7,4)
NanoMinigame:SetTargetActive(1,7,1)
NanoMinigame:SetTargetVolatile(1,7,0)
NanoMinigame:SetTargetColour(1,8,0)
NanoMinigame:SetTargetActive(1,8,0)
NanoMinigame:SetTargetVolatile(1,8,0)
NanoMinigame:SetTargetColour(1,9,0)
NanoMinigame:SetTargetActive(1,9,0)
NanoMinigame:SetTargetVolatile(1,9,0)
NanoMinigame:SetTargetColour(1,10,4)
NanoMinigame:SetTargetActive(1,10,1)
NanoMinigame:SetTargetVolatile(1,10,0)
NanoMinigame:SetTargetColour(1,11,0)
NanoMinigame:SetTargetActive(1,11,0)
NanoMinigame:SetTargetVolatile(1,11,0)
NanoMinigame:SetTargetSpeed(1,0.4)

MinigameManager:StartMiniGame(NanoMinigame)
end

global function doctorTrigger()
	local doctor=GetActor("doctor")
	local loc=FindNodeByName("loc_lab_panel") 
	doctor:Teleport(loc)
	local anim = FindNodeByShortName("EM_ANIMATOR_TheDoctor_Anim_DRW_InteractPanel1_2m")
	doctor:PlayAnim(anim,1,0.5)

end

global function Trigger()
	if(which_game == 1) then
		Easy()
	elseif(which_game == 2) then
		Medium()
	elseif(which_game == 0) then
		Tutorial()
	else
		Hard()
	end
end





global function AmyTrigger()
		local amy = GetActor("amy")
		local doctor = GetActor("doctor")
		
		doctor::[ IDLE TO TURN_IDLE]
		--nod, hand on hip
		local anim = FindNodeByShortName("EM_ANIMATOR_Amy_Anim_AMY_IdletoTurnValveIdle") --0.8s
		amy:PlayAnimAndWait(anim, 1, 0)
		
	
		
		doctor::[ TURN WHEEL]
		local anim = FindNodeByShortName("EM_ANIMATOR_Amy_Anim_AMY_TurnValve") -- 1.5s
		--nod
		amy:PlayAnimAndWait(anim, 1, 0)
		

		
		doctor::[ BACK TO IDLE]
		local anim = FindNodeByShortName("EM_ANIMATOR_Amy_Anim_AMY_TurnValveIdletoIdle") -- 1s
		--pray
		amy:PlayAnimAndWait(anim, 1, 1.0)
		amy:StopAnim(0.5)
		--amy:SetBehaviour("wait")

end


